### ISSUE TITLE
Data set issues

### ISSUE THREAD

**Issue by jianGao555** [WHU-USI3DV/EGIInet#2]
Downloaded the dataset, unzipped it with an error that prevented it from being unzipped, only 00 could be unzipped, the later ones could not be unzipped

**Comment by XuHang0806** [comment]
Run cat ShapeNetViPC-Dataset.tar.gz* | tar zx. Refer to https://github.com/Hydrogenion/ViPC for more detailed operation

**Comment by rigved-sanku** [comment]
I was unable to download the dataset from the mentioned link
It asks for login and requires a Chinese phone number for registration
Is there any new link for the dataset ?
email: sankurigved@gmail.com

**Comment by XuHang0806** [comment]
Sorry, we don't have the permission to publish the dataset elsewhere. You can get in touch with the author of ViPC.
