### ISSUE TITLE
Training code issues

### ISSUE THREAD

**Issue by Rinfly** [WHU-USI3DV/EGIInet#4]
Thank you for your work! But I can't find the code for the backward propagation. Also, `style_loss` in `train.py` is a tensor with 4 items, which makes an error in `total_cd_pc += cd_pc_item`.

**Comment by XuHang0806** [comment]
Thank you for your careful comment! This is an error during code reorganization, we have fix it.
The style_loss should be added up during forward function. This part only affects the display of the training process, and can be deleted if an error is reported.
