### ISSUE TITLE
Batchsize and Epoch ?

### ISSUE THREAD

**Issue by xinpuliu** [WHU-USI3DV/EGIInet#5]
Thank you for your excellent work in open source. 

I would like to ask what is the batch size for your experiment ?    I cannot find any relevant statements in the paper.

**Comment by xinpuliu** [comment]
and are all experiments's epoch=160?

**Comment by XuHang0806** [comment]
Batchsize=128 and Epoch=160 for all the categories, we take the best performance as final result.
