### ISSUE TITLE
Pre-training model of XMFNet

### ISSUE THREAD

**Issue by doldolOuO** [WHU-USI3DV/EGIInet#6]
Dear authors, could you provide the pre-train model of XMFNet under all eight categories?

**Comment by doldolOuO** [comment]
Thank you very much. Please send the pre-trained model to my email address (chenghaofang1014@163.com).

**Comment by XuHang0806** [comment]
Done. Please check your email in 7 days or it could be overdue.
To train on all eight categories, you can modify the ViPCDataloader.py. Let the dataloader read all paths of the eight categories during init stage.
